//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.lang {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TT.lang.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string Actualizar {
            get {
                return ResourceManager.GetString("Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liga.
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadio.
        /// </summary>
        internal static string Art_Inc {
            get {
                return ResourceManager.GetString("Art_Inc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calcular.
        /// </summary>
        internal static string Calcular {
            get {
                return ResourceManager.GetString("Calcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clubes.
        /// </summary>
        internal static string Canciones {
            get {
                return ResourceManager.GetString("Canciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grafica de clubes.
        /// </summary>
        internal static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presidente.
        /// </summary>
        internal static string Colab {
            get {
                return ResourceManager.GetString("Colab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulos.
        /// </summary>
        internal static string Duracion {
            get {
                return ResourceManager.GetString("Duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma.
        /// </summary>
        internal static string formP {
            get {
                return ResourceManager.GetString("formP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hallar Raiz.
        /// </summary>
        internal static string gbText {
            get {
                return ResourceManager.GetString("gbText", resourceCulture);
            }
        }
        
  
        /// <summary>
        ///   Busca una cadena traducida similar a Entrenador.
        /// </summary>
        internal static string Genero {
            get {
                return ResourceManager.GetString("Genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nada.
        /// </summary>
        internal static string nada {
            get {
                return ResourceManager.GetString("nada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Club.
        /// </summary>
        internal static string Nom_cancion {
            get {
                return ResourceManager.GetString("Nom_cancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liga:.
        /// </summary>
        internal static string NomArt {
            get {
                return ResourceManager.GetString("NomArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Club:.
        /// </summary>
        internal static string NomCancion {
            get {
                return ResourceManager.GetString("NomCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de clubes.
        /// </summary>
        internal static string Reg_canciones {
            get {
                return ResourceManager.GetString("Reg_canciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        internal static string Resul {
            get {
                return ResourceManager.GetString("Resul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar Idioma.
        /// </summary>
        internal static string Sel_idioma {
            get {
                return ResourceManager.GetString("Sel_idioma", resourceCulture);
            }
        }
    }
}
